// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXRpcgau5-Dx2HgExveE23Z1Vl2Vjmq58',
    appId: '1:99868031464:web:70a298e6ce64089172cc5d',
    messagingSenderId: '99868031464',
    projectId: 'fs-finance-fd527',
    authDomain: 'fs-finance-fd527.firebaseapp.com',
    storageBucket: 'fs-finance-fd527.appspot.com',
    measurementId: 'G-ZJE50Z53PZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzUdp_xq9HzqjFKPS3-tmWm6muodZjbsk',
    appId: '1:99868031464:android:f4c3693960655e9272cc5d',
    messagingSenderId: '99868031464',
    projectId: 'fs-finance-fd527',
    storageBucket: 'fs-finance-fd527.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9o7z4OMHjhEmV4JhhRHDd7Z-KcQAw3lE',
    appId: '1:99868031464:ios:4c36de25fb640c6972cc5d',
    messagingSenderId: '99868031464',
    projectId: 'fs-finance-fd527',
    storageBucket: 'fs-finance-fd527.appspot.com',
    iosClientId: '99868031464-bgfh13cmlrlu7s3enmbre3cg8fbk0dhh.apps.googleusercontent.com',
    iosBundleId: 'com.example.sgFinance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9o7z4OMHjhEmV4JhhRHDd7Z-KcQAw3lE',
    appId: '1:99868031464:ios:4c36de25fb640c6972cc5d',
    messagingSenderId: '99868031464',
    projectId: 'fs-finance-fd527',
    storageBucket: 'fs-finance-fd527.appspot.com',
    iosClientId: '99868031464-bgfh13cmlrlu7s3enmbre3cg8fbk0dhh.apps.googleusercontent.com',
    iosBundleId: 'com.example.sgFinance',
  );
}
